### ISSUE TITLE
Error on upload in call to wwv_flow.ajax

### ISSUE THREAD

**Issue by z3bull** [Dani3lSun/apex-plugin-dropzone#55]
### Expected behavior
The file to be uploaded and placed in the collection

### Actual behavior
This was working.  But now File appears to upload, but shows an error and a 403 response is received from the server

### Steps to reproduce the issue
N/A

### APEX version (4.2.6 / 5.0.3)
18.1

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)
Tomcat 9.0.13

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Chrome Version 70.0.3538.102 (Official Build) (64-bit)

![upload error](https://user-images.githubusercontent.com/1553336/48784025-6dc32800-eca7-11e8-9fc1-4325ced9e5fe.png)

### Error Page
Oracle REST Data Services
500 Internal Server Error
Debug Trace
[TE] url-mapping start: 2018-11-20T15:17:15.882Z duration: 3ms
Mapped request to mapping: |apex||
did not authenticate request
mapped request using: /*:PL/SQL to: |apex||
Choosing: oracle.dbtools.apex.ModApex as current candidate with score: PLSQLDispatchScore
==== Processing Request: ====
--Attributes--
oracle.dbtools.http.ecid = rFWhqDQqOYprVedrOe-Ncw..
ECID-Principal = ECIDPrincipal [ecid=rFWhqDQqOYprVedrOe-Ncw..]
oracle.dbtools.common.di.Services = URL Mapped Scope
oracle.dbtools.plugin.api.di.InstanceLocator = oracle.dbtools.common.di.Services$InstanceLocator@359055b8
oracle.dbtools.http.servlet.dispatch.score = PLSQLDispatchScore
--Attributes--
GET /ords/wwv_flow.ajax HTTP/1.1
Host: XXXXXXXXXXXXXXXXX
host: XXXXXXXXXXXXXXXXXX
connection: keep-alive
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
dnt: 1
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cookie: ORA_WWV_APP_498=OR__C7; ORA_WWV_APP_106=OR__ny; ORA_WWV_USER_218210578450070=OR__bF; ORA_WWV_APP_100=OR__Pa; __utma=18__.8; __utmc=18__35; _ga=GA__00

org.apache.catalina.connector.CoyoteInputStream@5206f049
Using Procedure:wwv_flow.ajax
SID: 163
PATCHING: APPLIED
isValidRequest(), procedure name: <wwv_flow.ajax>
Validating: wwv_flow.ajax
*** Total number of arguments: 61
** checkRequestValidationFunction(), <wwv_flow.ajax> exclude= false
Parse: 0 ms
-----
begin 
 wwv_flow.ajax;
commit;
  end;
*** Total number of arguments: 61

#### Error occurred in Signature for procedure: wwv_flow.ajax. Reloading...
*** Total number of arguments: 61
*** Total number of arguments: 61

EXEC FAILED:ORA-06550: line 2, column 2:
PLS-00306: wrong number or types of arguments in call to 'AJAX'
ORA-06550: line 2, column 2:
PL/SQL: Statement ignored
**java.sql.SQLException: ORA-06550: line 2, column 2:
PLS-00306: wrong number or types of arguments in call to 'AJAX'**
ORA-06550: line 2, column 2:
PL/SQL: Statement ignored

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:223)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:56)
	at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:907)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1300)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3887)
	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4230)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1079)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at oracle.ucp.jdbc.proxy.StatementProxyFactory.invoke(StatementProxyFactory.java:367)
	at com.sun.proxy.$Proxy74.execute(Unknown Source)
	at oracle.dbtools.apex.OWA.execute(OWA.java:184)
	at oracle.dbtools.apex.ModApex.handleRequest(ModApex.java:270)
	at oracle.dbtools.apex.ModApex.doGet(ModApex.java:139)
	at oracle.dbtools.apex.ModApex.service(ModApex.java:104)
	at oracle.dbtools.http.entrypoint.Dispatcher.dispatch(Dispatcher.java:125)
	at oracle.dbtools.http.entrypoint.EntryPoint$FilteredServlet.service(EntryPoint.java:239)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:73)
	at oracle.dbtools.http.forwarding.QueryFilteringRewrite.doFilter(QueryFilteringRewrite.java:90)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.forwarding.ForwardingFilter.doFilter(ForwardingFilter.java:68)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.cors.CORSPreflightFilter.doFilter(CORSPreflightFilter.java:66)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.cookies.auth.CookieSessionCSRFFilter.doFilter(CookieSessionCSRFFilter.java:75)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.auth.AuthenticationFilter.authenticate(AuthenticationFilter.java:101)
	at oracle.dbtools.http.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:64)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.url.mapping.RequestMapperImpl.doFilter(RequestMapperImpl.java:161)
	at oracle.dbtools.url.mapping.URLMappingBase.doFilter(URLMappingBase.java:96)
	at oracle.dbtools.url.mapping.filter.URLMappingFilter.doFilter(URLMappingFilter.java:127)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.auth.external.ExternalSessionFilter.doFilter(ExternalSessionFilter.java:59)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.rt.authentication.apex.ApexSessionQueryRewriteFilter.doFilter(ApexSessionQueryRewriteFilter.java:58)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.cors.CORSResponseFilter.doFilter(CORSResponseFilter.java:83)
	at oracle.dbtools.http.filters.HttpResponseFilter.doFilter(HttpResponseFilter.java:45)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.filters.AbsoluteLocationFilter.doFilter(AbsoluteLocationFilter.java:65)
	at oracle.dbtools.http.filters.HttpResponseFilter.doFilter(HttpResponseFilter.java:45)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.errors.ErrorPageFilter.doFilter(ErrorPageFilter.java:85)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.secure.ForceHttpsFilter.doFilter(ForceHttpsFilter.java:74)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.auth.ForceAuthFilter.doFilter(ForceAuthFilter.java:44)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.filters.Filters.filter(Filters.java:65)
	at oracle.dbtools.http.entrypoint.EntryPoint.service(EntryPoint.java:81)
	at oracle.dbtools.http.entrypoint.EntryPointServlet.service(EntryPointServlet.java:102)
	at oracle.dbtools.entrypoint.WebApplicationRequestEntryPoint.service(WebApplicationRequestEntryPoint.java:50)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: Error : 6550, Position : 8, Sql = begin 
 wwv_flow.ajax;
commit;
  end;, OriginalSql = begin 
 wwv_flow.ajax;
commit;
  end;, Error Msg = ORA-06550: line 2, column 2:
PLS-00306: wrong number or types of arguments in call to 'AJAX'
ORA-06550: line 2, column 2:
PL/SQL: Statement ignored

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	... 95 more
==== Request Processed ====
[TE] GET /ords/wwv_flow.ajax start: 2018-11-20T15:17:15.882Z duration: 354ms

		
Stack Trace
InternalServerException [statusCode=500, reasons=[]]
	at oracle.dbtools.apex.ModApexContext.handleError(ModApexContext.java:283)
	at oracle.dbtools.apex.OWA.execute(OWA.java:203)
	at oracle.dbtools.apex.ModApex.handleRequest(ModApex.java:270)
	at oracle.dbtools.apex.ModApex.doGet(ModApex.java:139)
	at oracle.dbtools.apex.ModApex.service(ModApex.java:104)
	at oracle.dbtools.http.entrypoint.Dispatcher.dispatch(Dispatcher.java:125)
	at oracle.dbtools.http.entrypoint.EntryPoint$FilteredServlet.service(EntryPoint.java:239)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:73)
	at oracle.dbtools.http.forwarding.QueryFilteringRewrite.doFilter(QueryFilteringRewrite.java:90)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.forwarding.ForwardingFilter.doFilter(ForwardingFilter.java:68)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.cors.CORSPreflightFilter.doFilter(CORSPreflightFilter.java:66)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.cookies.auth.CookieSessionCSRFFilter.doFilter(CookieSessionCSRFFilter.java:75)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.auth.AuthenticationFilter.authenticate(AuthenticationFilter.java:101)
	at oracle.dbtools.http.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:64)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.url.mapping.RequestMapperImpl.doFilter(RequestMapperImpl.java:161)
	at oracle.dbtools.url.mapping.URLMappingBase.doFilter(URLMappingBase.java:96)
	at oracle.dbtools.url.mapping.filter.URLMappingFilter.doFilter(URLMappingFilter.java:127)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.auth.external.ExternalSessionFilter.doFilter(ExternalSessionFilter.java:59)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.rt.authentication.apex.ApexSessionQueryRewriteFilter.doFilter(ApexSessionQueryRewriteFilter.java:58)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.cors.CORSResponseFilter.doFilter(CORSResponseFilter.java:83)
	at oracle.dbtools.http.filters.HttpResponseFilter.doFilter(HttpResponseFilter.java:45)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.filters.AbsoluteLocationFilter.doFilter(AbsoluteLocationFilter.java:65)
	at oracle.dbtools.http.filters.HttpResponseFilter.doFilter(HttpResponseFilter.java:45)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.errors.ErrorPageFilter.doFilter(ErrorPageFilter.java:85)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.secure.ForceHttpsFilter.doFilter(ForceHttpsFilter.java:74)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.auth.ForceAuthFilter.doFilter(ForceAuthFilter.java:44)
	at oracle.dbtools.http.filters.HttpFilter.doFilter(HttpFilter.java:47)
	at oracle.dbtools.http.filters.FilterChainImpl.doFilter(FilterChainImpl.java:64)
	at oracle.dbtools.http.filters.Filters.filter(Filters.java:65)
	at oracle.dbtools.http.entrypoint.EntryPoint.service(EntryPoint.java:81)
	at oracle.dbtools.http.entrypoint.EntryPointServlet.service(EntryPointServlet.java:102)
	at oracle.dbtools.entrypoint.WebApplicationRequestEntryPoint.service(WebApplicationRequestEntryPoint.java:50)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: ORA-06550: line 2, column 2:
PLS-00306: wrong number or types of arguments in call to 'AJAX'
ORA-06550: line 2, column 2:
PL/SQL: Statement ignored

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:223)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:56)
	at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:907)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1300)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3887)
	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4230)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1079)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at oracle.ucp.jdbc.proxy.StatementProxyFactory.invoke(StatementProxyFactory.java:367)
	at com.sun.proxy.$Proxy74.execute(Unknown Source)
	at oracle.dbtools.apex.OWA.execute(OWA.java:184)
	... 75 more
Caused by: Error : 6550, Position : 8, Sql = begin 
 wwv_flow.ajax;
commit;
  end;, OriginalSql = begin 
 wwv_flow.ajax;
commit;
  end;, Error Msg = ORA-06550: line 2, column 2:
PLS-00306: wrong number or types of arguments in call to 'AJAX'
ORA-06550: line 2, column 2:
PL/SQL: Statement ignored

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	... 95 more

		
About Oracle  Contact Us  Legal Notices  Terms Of Use  Your Privacy Rights
Copyright © 2014, 2018 Oracle and/or its affiliates All rights reserved.

**Comment by Dani3lSun** [comment]
Hey @z3bull 
what have you changed? As you´re saying that it working before...
Which upload method do you use?

**Comment by z3bull** [comment]
we are using 2.4.1  We think that because we are running 2 instances of ORDS on the same server, they may be conflicting with each other as this is not the only problem.  We are going to separate them and see if that resolves the problem.  I'll let you know the outcome.

**Comment by z3bull** [comment]
Well, it looks that has solved the the problem.  Apparently 2 instances of ORDS on the same webserver don't play well.  Thanks for the responses.
